name: Release

on:
  push:
    tags: ["**"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
        id: tag
      - run: gh release create '${{ steps.tag.outputs.tag }}' --notes 'See the [changelog](https://github.com/${{ github.repository }}/blob/${{ steps.tag.outputs.tag }}/CHANGELOG.md) for details.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
