name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  ruby-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
    steps:
      - id: versions
        run: |
          versions=$(curl -s 'https://cache.ruby-lang.org/pub/misc/ci_versions.json' | jq -c)
          echo "::set-output name=value::${versions}"

  test:
    name: Test on Ruby ${{ matrix.ruby }} and ${{ matrix.os }}
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: git config --global user.name '${{ github.actor }}'
      - run: git config --global user.email '${{ github.actor }}@users.noreply.github.com'
      - run: bundle exec rake
