name: Ruby Gem

on: [push]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  test:
    needs: [check_skip]
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle install
      run: |
        gem install bundler --no-document
        bundle install --jobs=4 --retry=3 --path=vendor/bundle
    - name: Setup Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Run tests
      run: bundle exec rake test
