name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          gem install bundler --no-document
          bundle config set path vendor/bundle
          bundle config set jobs 4
          bundle config set retry 3
          bundle install
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - run: bundle exec rake test
