name: TypeProf

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle config set with typecheck && bundle install
      - uses: ybiquitous/typeprof-action@main
        with:
          file: "lib/aufgaben/**/{release,ruby,nodejs}.rb"
